name: Teste de Build do Edson
on: [push]

jobs:
  verificacao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalando Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Instalando dependencias
        run: npm install
      - name: Testando o Build
        run: npm run build
